name: sars_cov_2
channels:
  - bioconda
  - anaconda
  - conda-forge
  - r
  - defaults
dependencies:
  - entrez-direct
  - blast
  - clustalw
  - sra-tools
  - fastp
  - fastqc
  - bcftools
  - bwa
  - samtools
  - csvkit
  - snp-sites
  - muscle
